title: "The Alignment Architect"
description: "Explorer les défis de la sûreté de l'IA pour construire des systèmes robustes"
theme: jekyll-theme-minimal
author: "Nemesis"  # ← Ajoutez cette ligne (votre pseudo ou nom réel)
